INSERT INTO characters (name, given_name, gender, race, age, height, threat, occupation, city, status) VALUES ("Bald Cape", "Saitama", "Male", "Human", "25", "1.75m", "N/A", "Hero", "Z", "Alive");
INSERT INTO characters (name, gender, race, height, threat, city, status) VALUES ("Vaccine Man", "Male", "Monster", "2-18m", "Dragon", "A", "Deceased");
INSERT INTO characters (name, gender, status, height, city, threat) VALUES ("Crablante", "Male", "Deceased", "2.5m", "Z", "Tiger");
INSERT INTO characters (name, race, status, city, gender) VALUES ("Cleft-Chinned Kid", "Human", "Alive", "Z", "Male");
INSERT INTO characters (name, race, status, city, gender, occupation) VALUES ("Fukegao", "Human", "Deceased", "D", "Male", "Scientist");
INSERT INTO characters (name, race, gender, status, height, city, threat) VALUES ("Marugori", "Mutant Human", "Male", "Deceased", "270m", "D", "Dragon");
INSERT INTO characters (name, race, gender, status, height, threat) VALUES ("Subterranean King", "Subterranean", "Male", "Deceased", "4m", "Demon");
INSERT INTO characters (name, race, gender, status, height, threat) VALUES ("Mosquito Girl", "Mutant", "Female", "Unknown", "2.6m", "Demon");
INSERT INTO characters (name, given_name, race, gender, age, status, height, city, occupation) VALUES ("Demon Cyborg", "Genos", "Human Cyborg", "Male", "19", "Alive", "1.78m", "Z", "Hero");
INSERT INTO characters (name, race, gender, status, age, occupation) VALUES ("Dr. Genus", "Human", "Male", "Alive", "100", "Scientist");
INSERT INTO characters (name, race, gender, status, threat) VALUES ("Kamakyuri", "Mutant", "Male", "Deceased", "Tiger");
INSERT INTO characters (name, race, gender, status, threat) VALUES ("Slugerous", "Mutant", "Male", "Deceased", "Tiger");
INSERT INTO characters (name, race, gender, status, threat) VALUES ("Frog Man", "Mutant", "Male", "Deceased", "Tiger");
INSERT INTO characters (name, race, gender, status, threat) VALUES ("Ground Dragon", "Mutant", "Male", "Deceased", "Tiger");
INSERT INTO characters (name, race, gender, status, threat, height) VALUES ("Armored Gorilla", "Cyborg Mutant", "Male", "Alive", "Demon", "3.1m");
INSERT INTO characters (name, race, gender, status, threat, height) VALUES ("Beast King", "Mutant", "Male", "Deceased", "Demon", "7m");
INSERT INTO characters (name, race, gender, status, height, city, threat) VALUES ("Piggie Bancon", "Monster", "Male", "Deceased", "2.2m", "Z", "Wolf");
INSERT INTO characters (name, race, gender, status, height, threat) VALUES ("Carnage Kabuto", "Mutant", "Male", "Deceased", "3.5-8.5m", "Dragon");
INSERT INTO characters (name, gender, race, height, city, status) VALUES ("Hammerhead", "Male", "Human", "2.15m", "F", "Alive");
INSERT INTO characters (name, gender, race, age, height, occupation, city, status) VALUES ("Mumen Rider", "Male", "Human", "25", "1.7m", "Hero", "Z", "Alive");
INSERT INTO characters (name, gender, race, occupation, city, status) VALUES ("Zeniru", "Male", "Human", "Millionaire", "F", "Alive");
INSERT INTO characters (name, gender, race, age, occupation, city, status) VALUES ("Speed-o'-Sound Sonic", "Male", "Human", "25", "Villain, Bodyguard", "Z", "Alive");
INSERT INTO characters (name, gender, race, height, threat, city, status) VALUES ("Personification of a Light Pull Cord", "Male", "Monster", "2.6m", "Tiger", "Z", "Deceased");
INSERT INTO characters (name, gender, race, age, height, occupation, city, status) VALUES ("Sneck", "Male", "Human", "37", "1.795m", "Hero, Martial Artist", "F", "Alive");
INSERT INTO characters (name, gender, race, age, height, occupation, status) VALUES ("Tank Top Tiger", "Male", "Human", "25", "2.202m", "Hero", "Alive");
INSERT INTO characters (name, gender, race, age, height, occupation, status) VALUES ("Golden Ball", "Male", "Human", "28", "1.95m", "Hero", "Alive");
INSERT INTO characters (name, gender, race, age, height, occupation, status) VALUES ("Spring Mustachio", "Male", "Human", "47", "1.78m", "Hero", "Alive");
INSERT INTO characters (name, gender, race, occupation, city, status) VALUES ("Watchdog Man", "Male", "Human", "Hero", "Q", "Alive");
INSERT INTO characters (name, gender, race, age, height, occupation, city, status) VALUES ("Heavy Kong", "Male", "Human", "29", "1.98m", "Hero", "W", "Unkown");
INSERT INTO characters (name, race, occupation, city, status) VALUES ("Mushroom", "Human", "Hero", "H", "Alive");
INSERT INTO characters (name, gender, occupation, city, status) VALUES ("Horse-Bone", "Male", "Hero", "H", "Alive");
INSERT INTO characters (name, given_name, gender, race, age, height, occupation, city, status) VALUES ("Lightning Genji", "Genji", "Male", "Human", "24", "1.65m", "Hero", "D", "Alive");
INSERT INTO characters (name, race, height, threat, city, status) VALUES ("Kombu Infinity", "Monster", "1.89m", "Tiger", "Z", "Alive");
INSERT INTO characters (name, race, age, height, threat, city, status) VALUES ("170,000-Year Magicicada Nymph", "Monster", "170000", "35m", "Demon", "Z", "Deceased");
INSERT INTO characters (name, gender, race, age, height, occupation, city, status) VALUES ("Darkness Blade", "Male", "Human", "20", "1.8m", "Hero", "Z", "Alive");
INSERT INTO characters (name, gender, race, age, height, occupation, status) VALUES ("Red Muffler", "Male", "Human", "20", "1.68", "Hero", "Alive");
INSERT INTO characters (name, gender, race, occupation, status) VALUES ("Grad School Graduate", "Male", "Human", "Hero", "Alive");
INSERT INTO characters (name, race, age, height, threat, city, status) VALUES ("170,000-Year Magicicada Adult", "Monster", "170000", "135m", "Demon", "Z", "Deceased");
INSERT INTO characters (name, gender, race, age, height, occupation, status) VALUES ("Sweet Mask", "Male", "Human", "24", "1.81m", "Hero, Model, Actor, Singer", "Alive");
INSERT INTO characters (name, gender, race, occupation, status) VALUES ("Glasses", "Male", "Human", "Hero", "Alive");
INSERT INTO characters (name, gender, race, occupation, status) VALUES ("Banero", "Male", "Human", "Villain", "Alive");
INSERT INTO characters (name, race, height, threat, city, status) VALUES ("Demonic Fan", "Monster", "1.7m", "Demon", "Z", "Deceased");
INSERT INTO characters (name, given_name, gender, race, age, height, occupation, status) VALUES ("Hellish Blizzard", "Fubuki", "Female", "Human", "23", "1.67m", "Hero", "Alive");
INSERT INTO characters (name, given_name, gender, race, age, height, occupation, status) VALUES ("Terrible Tornado", "Tatsumaki", "Female", "Human", "28", "N/A", "Hero", "Alive");
INSERT INTO characters (name, given_name, gender, race, age, height, occupation, status) VALUES ("Silver Fang", "Bang", "Male", "Human", "81", "1.65m", "Hero, Martial Arts Instructor", "Alive");
INSERT INTO characters (name, given_name, gender, race, occupation, status) VALUES ("Metal Knight", "Bofoi", "Male", "Human", "Hero, Scientist", "Alive");
INSERT INTO characters (name, gender, race, age, height, occupation, status) VALUES ("Tank Top Black Hole", "Male", "Human", "28", "2.133m", "Hero", "Alive");
INSERT INTO characters (name, gender, race, age, height, occupation, city, status) VALUES ("Stinger", "Male", "Human", "24", "1.84m", "Hero", "J", "Alive");
INSERT INTO characters (name, gender, race, height, threat, status) VALUES ("Deep Sea King", "Male", "Seafolk", "4-20m", "Demon", "Deceased");
INSERT INTO characters (name, given_name, gender, race, age, height, occupation, status) VALUES ("Lightning Max", "Max", "Male", "Human", "21", "1.78m", "Hero", "Alive");
INSERT INTO characters (name, gender, race, age, height, occupation, status) VALUES ("Puri-puri Prisoner", "Male", "Human", "33", "2.2m", "Hero", "Alive");
